// Standardpläne: 3 Hauptpläne + Sondertrainings 4a–4g. Positionen verweisen auf Katalog-IDs.
// Position: { kind: 'ex', uid, exId, sets, reps ('8-12' | '30-60 s' | Text), group ('A' = Superset A), note,
//   optional, perSide, variant (vorausgewählte Varianten-ID), stage (vorausgewählte Stufe, Index) }
// Abschnitt: { kind: 'section', uid, title }

const P = (id, name, kind, info, note, items) => ({
  id, name, kind, info, note,
  items: items.map((it, i) => ({ ...it, uid: `${id}-${i + 1}` })),
});
const sec = (title) => ({ kind: 'section', title });
// e(exId, sets, reps, { g, note, opt, side, v, st })
const e = (exId, sets, reps, o = {}) => ({
  kind: 'ex', exId, sets, reps, group: o.g || '', note: o.note || '', optional: !!o.opt, perSide: !!o.side,
  ...(o.v ? { variant: o.v } : {}), ...(o.st != null ? { stage: o.st } : {}),
});

export const DEFAULT_PLANS = [
  P('upper', 'Upper Body', 'main', 'Gym', '', [
    e('seitheben-kabel', 2, '12-20', { note: 'Priorität' }),
    e('schulteruebung', 2, '8-12', { note: 'Pike Pushups ODER 1x Schulterpresse + 1x Seitheben KH (Seitheben 12-20)' }),
    e('klimmzuege-weit', 3, '6-12'),
    e('obere-brust', 2, '8-12'),
    e('reverse-flys', 3, '12-20', { note: 'Priorität' }),
    e('mittlere-brust', 2, '8-12'),
    e('rudern', 3, '8-12'),
    e('untere-brust', 2, '8-12'),
    e('bizeps-kabel', 2, '10-15', { g: 'B', note: 'Superset am Kabelturm' }),
    e('trizeps-kabel', 2, '10-15', { g: 'B' }),
    sec('Griffkraft & Unterarme'),
    e('reverse-curls', 2, '10-15', { v: 'kabel', note: 'gleiche Station wie Bizeps/Trizeps' }),
    e('dead-hang', 2, '30-60 s', { note: 'Stange' }),
  ]),
  P('lower', 'Lower Body', 'main', 'Gym', '', [
    e('waden', 3, '10-15', { note: 'Priorität' }),
    e('beinpresse', 2, '8-12', { v: 'std', note: 'Füße hoch = mehr Gluteus' }),
    e('beinstrecker', 3, '10-15'),
    e('adduktoren', 3, '12-20'),
    e('abduktoren', 3, '12-20'),
    e('beinbeuger', 3, '10-15'),
    e('pistol-prep', 1, 'ca. 5 Min', { note: 'Dehnen, tiefe Squats, Bulgarian Squats' }),
    e('bauchmaschine', 4, '10-15'),
  ]),
  P('cali', 'Upper Body Calisthenics', 'main', 'Park', 'Supersets, 60-90 s Pause nach jeder Runde.', [
    sec('Schulterblock (Priorität)'),
    e('seitheben-kh', 2, '12-20', { g: 'A', note: 'nächste Variante ab 2x20' }),
    e('ring-reverse-flys', 3, '12-20', { g: 'A' }),
    e('pike-pushups', 2, '8-12', { g: 'B' }),
    e('klimmzuege-weit', 3, '6-12', { g: 'B' }),
    sec('Brust & Rücken'),
    e('decline-pushups', 2, '8-15', { g: 'C' }),
    e('ring-rows', 3, '8-15', { g: 'C' }),
    e('ring-pushups', 2, '8-15', { g: 'D' }),
    e('ring-bizeps', 2, '10-15', { g: 'D' }),
    e('dips', 2, '6-12', { g: 'E' }),
    e('ring-trizeps', 2, '10-15', { g: 'E' }),
    sec('Griffkraft & Unterarme'),
    e('dead-hang', 2, '30-60 s', { g: 'F', note: 'Stange' }),
    e('reverse-curls', 2, '10-15', { g: 'F', v: 'kh' }),
  ]),
  P('4a', '4a Kurz Upper Body', 'special', 'Gym · ca. 45 Min', '', [
    e('seitheben-kabel', 2, '12-20', { g: 'A' }),
    e('reverse-flys', 3, '12-20', { g: 'A', v: 'kabel' }),
    e('schulterdruecken', 2, '8-12', { v: 'kh-sitzend', note: 'KH-Schulterdrücken sitzend oder Pike Pushups' }),
    e('klimmzuege-weit', 2, '6-12'),
    e('obere-brust', 2, '8-12', { v: 'schraeg-kh', note: 'Schrägbank ca. 30°' }),
    e('untere-brust', 2, '8-12', { note: 'Dips oder Dip-Maschine' }),
    e('rudern', 2, '8-12', { note: 'Kabel sitzend oder Rudermaschine' }),
    e('bizeps-kabel', 1, '10-15', { g: 'B' }),
    e('trizeps-kabel', 1, '10-15', { g: 'B' }),
    e('reverse-curls', 2, '10-15', { v: 'kabel', opt: true }),
    e('dead-hang', 2, '30-60 s', { opt: true }),
  ]),
  P('4b', '4b Kurz Lower Body', 'special', 'Gym · ca. 40 Min', '', [
    e('waden', 3, '10-15', { v: 'beinpresse' }),
    e('beinpresse', 2, '8-12', { v: 'std', note: 'Alternative: Bulgarian Split Squats KH (pro Seite)' }),
    e('beinstrecker', 2, '10-15'),
    e('beinbeuger', 2, '10-15'),
    e('adduktoren', 2, '12-20', { g: 'C' }),
    e('abduktoren', 2, '12-20', { g: 'C' }),
    e('bauchmaschine', 3, '10-15'),
  ]),
  P('4c', '4c Ganzkörper Gym', 'special', 'Gym · ca. 85-90 Min', '', [
    e('seitheben-kabel', 2, '12-20', { g: 'A' }),
    e('reverse-flys', 3, '12-20', { g: 'A', v: 'kabel' }),
    e('waden', 3, '10-15', { v: 'beinpresse' }),
    e('beinpresse', 2, '8-12', { v: 'std' }),
    e('klimmzuege-weit', 2, '6-12'),
    e('obere-brust', 2, '8-12', { v: 'schraeg-kh' }),
    e('rudern', 2, '8-12', { note: 'Kabel oder Maschine' }),
    e('beinstrecker', 2, '10-15'),
    e('beinbeuger', 2, '10-15'),
    e('adduktoren', 2, '12-20', { g: 'C' }),
    e('abduktoren', 2, '12-20', { g: 'C' }),
    e('bizeps-kabel', 2, '10-15', { g: 'D' }),
    e('trizeps-kabel', 2, '10-15', { g: 'D' }),
    e('bauchmaschine', 3, '10-15'),
    e('dead-hang', 2, '30-60 s'),
  ]),
  P('4d', '4d Ganzkörper Calisthenics', 'special', 'ca. 20 Min zuhause + 35 Min Park', '', [
    sec('Teil 1 · Zuhause (vorher)'),
    e('seitheben-kh', 2, '12-20', { g: 'H', v: 'std' }),
    e('wade-einbeinig', 3, '10-15', { g: 'H', v: 'kh' }),
    e('ausfallschritte', 2, '8-12', { side: true }),
    e('rdl', 2, '10-15'),
    sec('Teil 2 · Park'),
    e('ring-reverse-flys', 3, '12-20', { g: 'A' }),
    e('beinheben', 3, '8-15', { g: 'A' }),
    e('klimmzuege-weit', 2, '6-12', { g: 'B' }),
    e('dips', 2, '6-12', { g: 'B' }),
    e('ring-pushups', 2, '8-15', { g: 'C' }),
    e('ring-rows', 2, '8-15', { g: 'C' }),
    e('dead-hang', 2, '30-60 s', { g: 'G', opt: true }),
    e('false-grip-hang', 2, '15-30 s', { g: 'G', opt: true }),
  ]),
  P('4e', '4e Kurz Upper Body Calisthenics', 'special', 'ca. 5 Min zuhause + 30 Min Park', '', [
    sec('Teil 1 · Zuhause'),
    e('seitheben-kh', 2, '12-20', { v: 'std' }),
    sec('Teil 2 · Park'),
    e('ring-reverse-flys', 3, '12-20', { g: 'A' }),
    e('pike-pushups', 2, '8-12', { g: 'A' }),
    e('klimmzuege-weit', 2, '6-12', { g: 'B' }),
    e('ring-pushups', 2, '8-15', { g: 'B' }),
    e('ring-rows', 2, '8-15', { g: 'C' }),
    e('dips', 2, '6-12', { g: 'C' }),
    e('ring-bizeps', 2, '10-15'),
    e('dead-hang', 2, '30-60 s', { g: 'G', opt: true }),
    e('false-grip-hang', 2, '15-30 s', { g: 'G', opt: true }),
  ]),
  P('4f', '4f Urlaubs-Ganzkörper', 'special', 'Ringe + Griffe · ca. 60 Min', '', [
    e('ring-y-raises', 2, '10-15', { g: 'A' }),
    e('ring-reverse-flys', 3, '12-20', { g: 'A' }),
    e('ring-pullups', 3, '6-15', { g: 'B', note: 'Ring Pullups oder Ring Rows' }),
    e('pike-pushups', 2, '8-12', { g: 'B', st: 1 }),
    e('ring-pushups', 2, '8-15', { g: 'C' }),
    e('ring-bizeps', 2, '10-15', { g: 'C' }),
    e('decline-pushups', 2, '8-15', { g: 'D' }),
    e('ring-trizeps', 2, '10-15', { g: 'D' }),
    e('ring-split-squats', 3, '10-20', { g: 'E', side: true }),
    e('wade-einbeinig', 3, '12-20', { g: 'E', v: 'kg' }),
    e('ring-hamstring', 2, '8-15', { g: 'F' }),
    e('ring-knee-tucks', 3, '10-15', { g: 'F' }),
    e('dead-hang', 2, '30-60 s', { g: 'G', st: 1, note: 'Ring Dead Hang' }),
    e('fingertip-plank', 2, '20-40 s', { g: 'G' }),
  ]),
  P('4g', '4g Kurzhantel-Ganzkörper zuhause', 'special', 'ca. 65 Min', '', [
    e('seitheben-kh', 2, '12-20', { g: 'A', v: 'std' }),
    e('reverse-flys', 3, '12-20', { g: 'A', v: 'kh-vorgebeugt' }),
    e('schulterdruecken', 2, '8-12', { g: 'B', v: 'kh-stehend' }),
    e('rudern', 3, '8-12', { g: 'B', v: 'kh-vorgebeugt' }),
    e('deficit-pushups', 2, '8-15', { g: 'C' }),
    e('kh-bizeps', 2, '10-15', { g: 'C' }),
    e('kh-floor-press', 2, '8-12', { g: 'D' }),
    e('kh-trizeps', 2, '10-15', { g: 'D' }),
    e('ausfallschritte', 2, '8-12', { g: 'E', side: true }),
    e('wade-einbeinig', 3, '10-15', { g: 'E', v: 'kh' }),
    e('rdl', 3, '10-15', { g: 'F' }),
    e('kh-crunches', 3, '10-15', { g: 'F' }),
    e('farmers', 2, '30-60 s', { g: 'G', note: 'mit Kurzhanteln' }),
    e('reverse-curls', 2, '10-15', { g: 'G', v: 'kh' }),
  ]),
];

export const MAIN_PLAN_IDS = ['upper', 'lower', 'cali'];
